
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: exam
  datasource:
    url: jdbc:h2:file:D:/others/Learing/h2/exam/exam-service;DB_CLOSE_DELAY=-1;
    username: lang
    password: lang123
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 50
      connection-timeout: 20000 # 20 seconds
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1200000 # 20 minutes
      leak-detection-threshold: 60000 # 1 minute (lifesaver for debugging)

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update